### ISSUE TITLE
./lrzip -z COPYING segfautls

### ISSUE THREAD

**Issue by ppisar** [ckolivas/lrzip#47]
The lrzip-0.621 has no tests. I tried to add a simple round-trip test into Fedora package that does:

~~~~
./lrzip -z COPYING
./lrzip --info COPYING.lrz
./lrzip -d -o COPYING.new COPYING.lrz
cmp COPYING COPYING.new
~~~~

and it turned out that the compression command segfaults at the end of compression on ARMv7. See [https://kojipkgs.fedoraproject.org//work/tasks/5807/13035807/build.log]. It happens even with GCC 5 without the patch from issue #4:

~~~~
------------------------------------------------------------------------
lrzip 0.621
------------------------------------------------------------------------
Configuration Options Summary:
  ASM.(32 bit only)..: no
  Static binary......: no
Documentation..........: no
Compilation............: make (or gmake)
  CPPFLAGS.............: 
  CFLAGS...............: -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard
  CXXFLAGS.............: -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard
  LDFLAGS..............: -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr
+ make -j4
[...]
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.c7AUDz
+ umask 022
+ cd /builddir/build/BUILD
+ cd lrzip-0.621
+ ./lrzip -z COPYING
Output filename is: COPYING.lrz
Total:  1%  Chunk:  1%
Total:  2%  Chunk:  2%
[...]
Total: 98%  Chunk: 98%
Total: 99%  Chunk: 99%
/var/tmp/rpm-tmp.c7AUDz: line 31: 24743 Segmentation fault      (core dumped) ./lrzip -z COPYING
~~~~

I have no opportunity to debug it. I just want to notify you about this issue. Maybe you will have some idea.

**Comment by ppisar** [comment]
Actually I'm able to reproduce it on ARMv6 where I have interactive access. It raises SIGILL there. I'm not sure if this is the same issue:

~~~~
Program received signal SIGILL, Illegal instruction.
0x4002200c in ?? ()
(gdb) bt
#0  0x4002200c in ?? ()
#1  0x0003b214 in libzpaq::Encoder::compress (this=0x44bb7498, c=0)
    at libzpaq/libzpaq.cpp:1409
#2  0x0003b454 in libzpaq::Compressor::postProcess (
    this=this@entry=0x44bb7424, pcomp=pcomp@entry=0x0, len=len@entry=0)
    at libzpaq/libzpaq.cpp:1548
#3  0x0003b7dc in libzpaq::compress (in=0x44bced08, in@entry=0x44bced00, 
    out=0x44bcecfc, out@entry=0x44bcecf4, level=2, level@entry=17518)
    at libzpaq/libzpaq.cpp:1597
#4  0x0003b950 in zpaq_compress (c_buf=c_buf@entry=0x44c00468 "zPQ\001\001E", 
    c_len=c_len@entry=0x44bcee10, s_buf=<optimized out>, 
    s_len=s_len@entry=17518, level=2, msgout=0x403cbd58 <_IO_2_1_stdout_>, 
    progress=true, thread=thread@entry=0) at libzpaq/libzpaq.h:526
#5  0x00023894 in zpaq_compress_buf (thread=<optimized out>, cthread=0x66800, 
    control=0x5d7f8 <local_control>) at stream.c:184
#6  compthread (data=0x0) at stream.c:1296
#7  0x40099178 in start_thread () from /lib/libpthread.so.0
#8  0x40368968 in ?? () from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) list
1404          encode(1, 0);
1405        else {
1406          assert(c>=0 && c<=255);
1407          encode(0, 0);
1408          for (int i=7; i>=0; --i) {
1409            int p=pr.predict()*2+1;
1410            assert(p>0 && p<65536);
1411            int y=c>>i&1;
1412            encode(y, p);
1413            pr.update(y);
~~~~

If I proceed the next to line 1409, it crashes. Stepping into the pr.predict() call looks like:

~~~~
1409            int p=pr.predict()*2+1;
(gdb) s
libzpaq::Predictor::predict (this=0x44bb74a4) at libzpaq/libzpaq.cpp:3133
3133      if (!pcode) {
(gdb) n
3129    int Predictor::predict() {
(gdb)
3133      if (!pcode) {
(gdb)
3134        int n=assemble_p();
(gdb)
3135        allocx(pcode, pcode_size, n);
(gdb)
3134        int n=assemble_p();
(gdb)
3135        allocx(pcode, pcode_size, n);
(gdb)
3136        if (!pcode || n!=assemble_p() || n<10 || pcode_size<10)
(gdb)
3140      return ((int(*)(Predictor*))&pcode[0])(this);
(gdb)
3142    }
(gdb)
3140      return ((int(*)(Predictor*))&pcode[0])(this);
(gdb)
0x40022000 in ?? ()
(gdb)
Cannot find bounds of current function
~~~~

I did not know there is a JIT.

**Comment by ppisar** [comment]
I see it's the bundled ZPAQ. Unfortunately the bundled 5.0 version if very old. Upstream has 7.05. It would be great if were able to rebase the bundle.

**Comment by ppisar** [comment]
The JIT is supported on x86 and x86_64 only. One needs to pass CPPFLAGS=-DNOJIT to configure on other platforms.

**Comment by ckolivas** [comment]
The upstream newer libzpaq always produces corrupt archives for me so I've been unable to update to the latest version which is why I'm stuck with this version.

**Comment by ckolivas** [comment]
Disabling JIT in case anyone is still compiling for ARM.
